### ISSUE TITLE
Does Microsoft Graph compatibility present?

### ISSUE THREAD

**Issue by mediaexplorer74** [behl1anmol/Todo.me#6]
Hi! Nice app.
One dev question: what's about MS Todo api compatibility?

**Comment by behl1anmol** [comment]
Hi!
The app does not have Microsoft graph compatibility. It is a rather a standalone application with it an SQLite database.

**Comment by mediaexplorer74** [comment]
> Hi! The app does not have Microsoft graph compatibility. It is a rather a standalone application with it an SQLite database.

Ok. Thank you for your  help / advice.
EFCore branch -- xamarin forms, Master branch -- MAUI? 
I am big fan of old retro devices such as Nokia/MS Lumia. I m triing to recove the blocked MS TODO App.... but I have not enough C# skills .... I'm tring to find the "good and simple" XF / UWP template ) Your work looks promising... but the code is so modern )

**Comment by behl1anmol** [comment]
Hi,
Both EFCore and master branch are based on MAUI. MAUI is an evolution of Xamarin Forms, and most of the concepts remain same. You can easily make a switch to MAUI without any major concerns. It also provides a better way for managing cross platform code.

We do have an MS Todo App. Can you please specify what are you trying to recover?

Thanks,
Anmol

**Comment by mediaexplorer74** [comment]
> MAUI is an evolution of Xamarin Forms, and most of the concepts remain same. You can easily make a switch to MAUI without any major concerns. It also provides a better way for managing cross platform code.

Anmol Behl, 
ohhh... I see ) But MAUI is not compatible with obsolete Windows SDK 15063 :( So, no way to create any MAUI app for old/obsolete/fully cancelled-by-MS/"killed-by-creator" Windows 10 Mobile OS... ;)))))))))))))) Some world hackers (i.e., great XBOX reverse-engeneer Empyrial96: https://github.com/Empyreal96/W10M-16212-Guides) tried to improve W10M builds but no great success... MAUI needs min. win. sdk 17xxx as I know.

> We do have an MS Todo App. 

Wow, are you reverse engeneered whole MS ToDo app? Holly shit! ))) I need this UWP app very much ;) 
Seems to be MS used ReactUI... Its very hard level of coding... I cannot reccover this cool UI at all :(((((((((
![image](https://user-images.githubusercontent.com/12032735/218941766-839f2968-48c2-4b63-a95f-ac5f6e1ee582.png)

My "progress" is only basic Xamarin Forms app: https://github.com/mediaexplorer74/MSTodoX

Ready: 
- MS auth 
- "Task groups"

Not ready:
- Single task view page
- CRUD for any task

It 's to be very nice if you can to add "Show task" function into my app prototype..

> Can you please specify what are you trying to recover?

The answer to your main question: MS decided to "switch off" the Task "cloud sync" (via Microsoft Graph) for "mobile" Microsoft TODO (UWP app for Lumia phones with W10M). 

EOL: Feb, 15 2022. So, when I create any "fresh" task at my Deskop version of MS ToDo... then I cannot to see/edit that task via my sweet old mobile device. I'm too stupid developer, heh :) In theory, It's simple task... but... at/in practice, it's no good. :))

Cheers up,
MediaExplorer

P.S. Sorry for my poor English language / Thanx for your patience ))

**Comment by behl1anmol** [comment]
Hi
We did not re-engineered any app. I was just pointing out that MS has a todo app. I can now understand the point why you are creating the application. 
I consider myself as a beginner in mobile space might not be able to deep dive in the implementation you have requested.
Thanks,
Anmol
